name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: |
          julia -e 'using Pkg, CompatHelper; CompatHelper.main(;
            registries = [Pkg.RegistrySpec(name = "General",
                                  uuid = "23338594-aafe-5451-b93e-139f81909106",
                                  url = "https://github.com/JuliaRegistries/General.git"),
                          Pkg.RegistrySpec(name = "SuiteSplinesRegistry",
                                  uuid = "df7358ec-30c0-41d2-becf-685aef48513c",
                                  url = "https://github.com/SuiteSplines/SuiteSplinesRegistry.git")])'
